/* DROP TABLE */

/* TAULES NASCUDES PER RELACIONS */
DROP TABLE IF EXISTS Tipus_Passi_Atraccio;
DROP TABLE IF EXISTS Info_Utilitzacio;
DROP TABLE IF EXISTS Entrada_Parc;

/* TAULES NORMALS */
DROP TABLE IF EXISTS Entrada;
DROP TABLE IF EXISTS Passi_Express;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Tipus_Passi_Express;

ALTER TABLE Atraccio 
DROP FOREIGN KEY FK_Atraccio_Incidencia;

DROP TABLE IF EXISTS Incidencia;
DROP TABLE IF EXISTS Atraccio;
DROP TABLE IF EXISTS Zona;
DROP TABLE IF EXISTS Parc;
DROP TABLE IF EXISTS Preus;
DROP TABLE IF EXISTS Tipus_Acces;